# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2021-01-26 10:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField()),
                ('archived', models.DateTimeField(blank=True, null=True)),
                ('added', models.DateTimeField()),
                ('added_by', models.TextField()),
            ],
            options={
                'db_table': 'dataset',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatasetLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri_scheme', models.TextField()),
                ('uri_body', models.TextField()),
                ('added', models.DateTimeField()),
                ('added_by', models.TextField()),
            ],
            options={
                'db_table': 'dataset_location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatasetType',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField()),
                ('definition', django.contrib.postgres.fields.jsonb.JSONField()),
                ('added', models.DateTimeField()),
                ('added_by', models.TextField()),
            ],
            options={
                'db_table': 'dataset_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetadataType',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('definition', django.contrib.postgres.fields.jsonb.JSONField()),
                ('added', models.DateTimeField()),
                ('added_by', models.TextField()),
            ],
            options={
                'db_table': 'metadata_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IngestionDetails',
            fields=[
                ('dataset_type_ref', models.IntegerField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=100)),
                ('platform', models.CharField(default='', max_length=100)),
                ('global_dataset', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start_date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end_date')),
                ('latitude_min', models.FloatField(default=0)),
                ('latitude_max', models.FloatField(default=0)),
                ('longitude_min', models.FloatField(default=0)),
                ('longitude_max', models.FloatField(default=0)),
                ('pixel_count', models.BigIntegerField(default=0)),
                ('scene_count', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='IngestionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('db_name', models.CharField(default=uuid.uuid4, max_length=50)),
                ('dataset_type_ref', models.SmallIntegerField()),
                ('ingestion_definition', django.contrib.postgres.fields.jsonb.JSONField()),
                ('start_date', models.DateField(verbose_name='start_date')),
                ('end_date', models.DateField(verbose_name='end_date')),
                ('latitude_min', models.FloatField()),
                ('latitude_max', models.FloatField()),
                ('longitude_min', models.FloatField()),
                ('longitude_max', models.FloatField()),
                ('total_storage_units', models.IntegerField(default=0)),
                ('storage_units_processed', models.IntegerField(default=0)),
                ('download_script_path', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='WAIT', max_length=50)),
                ('message', models.CharField(default='Please wait while your Data Cube is created.', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='DatasetSource',
            fields=[
                ('dataset_ref', models.ForeignKey(db_column='dataset_ref', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='dataset_ref', serialize=False, to='data_cube_manager.Dataset')),
                ('classifier', models.TextField()),
            ],
            options={
                'db_table': 'dataset_source',
                'managed': False,
            },
        ),
    ]
